# Generated by Django 5.2.5 on 2025-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_author_unique_name_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='unique_name_email',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('name', 'lastname'), name='unique_name_email'),
        ),
    ]
