# Generated by Django 5.2.5 on 2025-08-24 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
