# Generated by Django 5.2.5 on 2025-08-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coment',
            new_name='Comment',
        ),
        migrations.RemoveConstraint(
            model_name='author',
            name='unique_name_email',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('name', 'lastname'), name='unique_name_lastname'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
